### ISSUE TITLE
HTML/CSS properties should not be camel-cased

### ISSUE THREAD

**Issue by rads** [escherize/huff#1]
From `readme.md`:

```clojure
(h/html [:div {:style {:border "1px red solid"
                       :background-color "#ff00ff"}}])
;; => "<div style=\"backgroundColor:#ff00ff;border:1px red solid;\"></div>"
```

The style above isn't valid CSS. The `backgroundColor` attribute should actually be `background-color`.

**Comment by rads** [comment]
I'm also wondering about the purpose of camel-casing HTML attribute names. There are a few use cases where HTML attributes can have hyphens in them (`accept-charset`, `http-equiv`, `data-foo-bar`). I'm not aware of any HTML attributes that are actually camel-cased.

I think attribute names should be converted from a keyword to a string but otherwise left alone.

**Comment by escherize** [comment]
Thanks for the report, I think these are good changes to make

**Comment by escherize** [comment]
We now have html and style attributes not being camel cased automatically, in #3.
