### ISSUE TITLE
Appending px to inappropriate CSS attributes

### ISSUE THREAD

**Issue by martinklepsch** [escherize/huff#14]
Hey! Thanks for making huff! 

I noticed that for 

```
:style {:opacity 1}
```

Huff will append "px" to the numeric value. I mostly just gave this a go after reading about it in the README and thinking that it's probably difficult to support this properly (i.e. know user intent). 

I think I'd be fine without this feature or maybe it being a "plugin" via the extensible grammar mechanism?

**Comment by escherize** [comment]
Hey, that's a good point! Thanks for bringing it up @martinklepsch. 

I think you have an escape hatch by stringifying your opacity value above:

```
(html [:div {:style {:opacity "1"}}])
;; => "<div style=\"opacity:1;\"></div>"
```

If required, a nice way to handle it is to _only_ convert `px-ey` keys where the values are numberic:

# `px-ey` keys would be:

    Width and Height:
        width
        height
        max-width
        max-height
        min-width
        min-height

    Margin and Padding:
        margin
        margin-top
        margin-right
        margin-bottom
        margin-left
        padding
        padding-top
        padding-right
        padding-bottom
        padding-left

    Borders:
        border-width
        border-top-width
        border-right-width
        border-bottom-width
        border-left-width

    Font and Text:
        font-size
        text-indent
        letter-spacing
        word-spacing

    Positioning:
        top
        right
        bottom
        left

    Box Model:
        border-radius
        border-spacing

    Shadows:
        box-shadow
        text-shadow

    Background:
        background-size

    Transforms:
        translateX
        translateY
        translateZ

    Outlines:
        outline-width

    List Styles:
        list-style-position

    Others:
        object-position


What do you think?

**Comment by escherize** [comment]
Good idea. I have done this, and also added convenience functions (tests here: https://github.com/escherize/huff/blob/master/test/huff/core2_test.clj#L166) to convert to px, em, etc.
