### ISSUE TITLE
huff2.core/html should maybe return RawString

### ISSUE THREAD

**Issue by piranha** [escherize/huff#15]
...or something equivalent. That's what [hiccup2.core/html](https://github.com/weavejester/hiccup/blob/master/src/hiccup2/core.clj) does, at least - this allows you to use functions which use `(html ..)` inside without their result being escaped.

Functions like that:

```
(defn head []
  (h/html
    [:head
     [:meta {:charset "utf-8"}]
     [:meta {:name "viewport" :content "width=device-width, initial-scale=1"}]]))
```

**Comment by escherize** [comment]
Closed as of v 0.2.12. We return raw strings as does hiccup, so users can compile html via h2/html and pass that to another call of h2/html.
