### ISSUE TITLE
Consider replacing `[:hiccup/raw-html]` with a `huff.core/raw` function

### ISSUE THREAD

**Issue by rads** [escherize/huff#5]
**Problem:**
It should not be possible to encode raw strings in EDN.
```clojure
(require '[clojure.edn :as edn]
         '[huff.core :as h])

;; Let's say we're reading some EDN on the server sent by the frontend

;; Seems harmless right?
(h/html [:div "Your name is: " (:name (edn/read-string "{:name \"Foo\"}"))])
;=> "<div>Your name is: Foo</div>"

;; HTML injection
(h/html [:div "Your name is: " (:name (edn/read-string "{:name [:hiccup/raw-html \"<script>alert('hi');</script>\"]}"))])
;=> "<div>Your name is: <script>alert('hi');</script></div>"
```

**Solution:**
Use the same approach that Hiccup takes: add a `huff.core/raw` function to construct raw strings. Remove the `[:hiccup/raw-html]` form to prevent the above example from being possible.

**Comment by rads** [comment]
@escherize: I see that the `[:hiccup/raw-html]` tag is now opt-in, which makes sense. That said, I still think it would be good to add a `huff.core/raw` function to allow users to add raw HTML fragments when `:allow-raw` is `false`.

For example, I'm currently using Huff in a Ring middleware to allow handler functions to return Hiccup. I want to make it so people using this middleware don't have to worry about HTML injection from external sources so I'm setting `:allow-raw` to `false`. The problem is then they don't have a way to add any raw HTML of their own without setting `:allow-raw` to `true`.

The `hiccup2.core/raw` function is an example of a more granular approach that's still secure. This is because the function returns an opaque value that has to be created from code and can't be injected simply by reading external data.

**Comment by escherize** [comment]
huff2.core now has raw-strings!

I thought hiccup's implementation was solid so I lifted it directly.

Code: 
- https://github.com/escherize/huff/blob/master/src/huff2/core.clj#L8
- https://github.com/escherize/huff/blob/master/src/huff2/core.clj#L47-L49
- https://github.com/escherize/huff/blob/master/src/huff2/core.clj#L224

Usage:

```clojure
(h/html [:div [:hiccup/raw-html (h/raw-string "<!-- oops.")]])
;; => <div><!-- oops.</div>
```

**Comment by rads** [comment]
@borkdude: Yeah, that’s a good point that I overlooked when I reported this issue. You can replace the raw data with a `:script` directly and it’s the same thing.

If anyone else reads this, the correct solution is to sanitize all user input. The `hiccup.core/raw` approach is not more secure than `[:hiccup/raw-html]`. For example if you render arbitrary EDN as Hiccup, you can also add JavaScript to any Hiccup tag via an attribute.
